### ISSUE TITLE
use trpc-swr

### ISSUE THREAD

**Issue by Udit-takkar** [lagonapp/lagon#118]
in https://github.com/lagonapp/lagon/pull/40  @QuiiBz  you refactored to trpc. we can also use trpc-swr (https://github.com/sachinraja/trpc-swr) where all useSwr was used before to get the continue getting caching benefits of useSwr.

**Comment by QuiiBz** [comment]
Hi @Udit-takkar, any reason for closing the issue?

**Comment by Udit-takkar** [comment]
I found trpc also uses react-query under the hood which also provides caching
