### ISSUE TITLE
Clap v4

### ISSUE THREAD

**Issue by QuiiBz** [lagonapp/lagon#157]
Update from clap v3 to clap v4, which provides an easier API and changes the output of help, among others. See https://epage.github.io/blog/2022/09/clap4/

**Comment by G3root** [comment]
are you working on this ?

**Comment by QuiiBz** [comment]
> are you working on this ?

Not yet, the status in the roadmap in still in TODO: https://github.com/orgs/lagonapp/projects/1

Happy to assign you if you want to start working on it :)

**Comment by G3root** [comment]
yeah i'll give it a try.

**Comment by QuiiBz** [comment]
> yeah i'll give it a try.

Just assigned you to this issue! Feel free to join the [Discord](https://discord.lagon.app/) if you need help/have questions.

**Comment by G3root** [comment]
i have joined the discord. i'll let you know if i get into a bummer.
