### ISSUE TITLE
GitHub deployments

### ISSUE THREAD

**Issue by QuiiBz** [lagonapp/lagon#16]
Deploy functions on push, similar to Vercel/Netlify in a GH Action.

**Comment by Udit-takkar** [comment]
can you assign it to me @QuiiBz ?

**Comment by QuiiBz** [comment]
> can you assign it to me @QuiiBz ?

Done! Feel free to chat on the Discord you have any questions

**Comment by QuiiBz** [comment]
Hello @Udit-takkar! I'm wondering if you have any news to share on this issue?

**Comment by QuiiBz** [comment]
Completed by @20k-ultra in https://github.com/lagonapp/github-action/pull/1, thanks!
