### ISSUE TITLE
atob/bto case inversion

### ISSUE THREAD

**Issue by cyco130** [lagonapp/lagon#229]
**Describe the bug**
`atob` and `btoa` seem to encode/decode with the wrong letter case **even though the implementation in the `js-runtime` package works correctly**. 

**To Reproduce**
Execute the following code:

```js
console.log(btoa("2")); // prints "mG=="
```

**Expected behavior**
It should print `Mg==` instead.

**Information:**
 - OS: Linux Mint x64
 - 0.3.4

**Comment by QuiiBz** [comment]
Strange bug. I was thinking about moving the base64 transforms to Rust code, which should be a lot faster for medium/big input.

The bug might be due to the string conversion in utf8 from JS to Rust.

**Comment by cyco130** [comment]
Copying the implementation into the user source file and doing `btoa = function btoa(...) { /* copied implementation */ }` to overwrite the builtin version fixes it. I don't know what it implies but maybe you do :)

Also `globalThis.btoa = function btoa...` doesn't overwrite plain global `btoa` for some reason.

**Comment by QuiiBz** [comment]
Strangely I'm not able to reproduce your output with the given code sample:

![Screenshot 2022-11-02 at 22 20 12](https://user-images.githubusercontent.com/43268759/199604682-2189d250-9412-4d70-b473-3509f6185c7e.png)

It prints `Mg==` for an input of `"2"`, not `mG==`. I'm also using the latest version of the CLI, but on macOS instead of Linux. Will try tomorrow on a Linux VM, but that seems really strange.

**Comment by cyco130** [comment]
Strange indeed. I really have no idea what could be going on here :/

**Comment by QuiiBz** [comment]
I tried on Linux (Ubuntu 20.04, my [screenshot from before](https://github.com/lagonapp/lagon/issues/229#issuecomment-1301295943) was on macOS), and still not reproducing the issue. It prints `Mg==` as expected:

![Screenshot 2022-11-05 at 15 57 55](https://user-images.githubusercontent.com/43268759/200126076-c4a18f05-f6ea-454e-95f6-6e337e8115aa.png)

**Comment by cyco130** [comment]
Great, now it's a mystery instead of a bug report :)

I'll uninstall and reinstall everything and hop it goes way.

**Comment by cyco130** [comment]
Reinstalled bunch of `apt` packages and `@lagon/cli@0.3.5` and it went away. Closing since I can't provide a reliable repro, very strange :)

(This leaves `index.html` and `FormData` issues as the only failing cases on Rakkas's CI tests)
