### ISSUE TITLE
Support Nitro

### ISSUE THREAD

**Issue by QuiiBz** [lagonapp/lagon#258]
Nitro is an universal way to build and deploy JavaScript apps: https://github.com/unjs/nitro

**Comment by aggmoulik** [comment]
Hey @QuiiBz I want to try the support with nitro. Is there any already researched steps in your mind, it will be great.

**Comment by QuiiBz** [comment]
Hello! I'm assigning the issue to you. I've never used Nitro, but looking at the docs it seems like Cloudflare Workers is supported, meaning Nitro can bundle for both Node.js and edge runtimes.

We'll have to look at how the [Cloudflare Workers provider](https://nitro.unjs.io/deploy/providers/cloudflare) works and replicate the same with Lagon. Note that:
- Lagon supports static files without additional logic inside the Function's code https://docs.lagon.app/cloud/static-files
- The bundled Function should export an `handler` function, that accepts a `Request` and return a `Response` https://docs.lagon.app/runtime-apis#handler
- It's possible to try if the bundled Function works by using Lagon's CLI with `lagon dev` https://docs.lagon.app/cli#lagon-dev (should be something similar to `lagon dev dist/server/index.js --public dist/public`)

**Comment by QuiiBz** [comment]
Hi @aggmoulik, did you get the time to work on this issue yet? @danielroe is interested to land support for Lagon in Nitro.

**Comment by pi0** [comment]
Nitro maintainer here. Is there a way for me to have access to the platform and try deployments?

**Comment by danielroe** [comment]
@pi0 Will add you to my dashboard.

**Comment by pi0** [comment]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/5158436/220209730-83132408-0b54-4f89-bf03-cb44fb4cc762.png">

**Comment by QuiiBz** [comment]
> Nitro maintainer here. Is there a way for me to have access to the platform and try deployments?

I’ll need your GitHub email to whitelist your account, you’ll then be able to deploy using the CLI. Note that you can also use `lagon dev` to run a dev server locally!

**Comment by pi0** [comment]
Thanks @QuiiBz. Yes i have tried it locally. My gh email are pooya@pi0.io and pyapar at gmail.

We just landed preset to the edge channel btw. Would be happy to have a chat about next steps when you had time 😊

**Comment by QuiiBz** [comment]
Thanks, you should now be able to log in to the dashboard and the CLI using `lagon login`. Feel free to join the [discord](https://discord.lagon.dev) if you have any issues!

**Comment by aggmoulik** [comment]
Hey @QuiiBz I was not able to try it for the support for Nitro. Looking forward to the implementation.

**Comment by rishi-raj-jain** [comment]
Can I also get access to Lagon? Would love to try out and contribute to the project!
