### ISSUE TITLE
Use radix-ui instead of headless-ui for Menu component

### ISSUE THREAD

**Issue by QuiiBz** [lagonapp/lagon#339]
We're switch from [`@headlessui/react`](https://headlessui.com/) to [`radix-ui`](https://www.radix-ui.com/).

The last component using headless-ui is `Menu` which can be replaced by the [Dropdown Menu](https://www.radix-ui.com/docs/primitives/components/dropdown-menu) from radix-ui. Then we can uninstall `@headlessui/react`

**Comment by asharonbaltazar** [comment]
Hey, would you mind if I take a shot at this? Seems pretty simple, and it'd be a good way to acquiant myself with an interesting project.

**Comment by QuiiBz** [comment]
Hey, of course! Assigning the issue to you.

**Comment by asharonbaltazar** [comment]
Sweet, thanks. Do you have a README for development?

**Comment by QuiiBz** [comment]
Yes, we a a [contributing documentation](https://docs.lagon.app/contributing). Since this issue is about a design system component, you can use the `dev` script inside `packages/ui` to start the storybook.
