### ISSUE TITLE
Replace `useTailwind` by `cva` in design system

### ISSUE THREAD

**Issue by QuiiBz** [lagonapp/lagon#352]
To customize the design system components, we made a `useTailwind` hook.

But I recently discovered [cva](https://github.com/joe-bell/cva) which is really better for this sort of stuff. We should remove this `useTailwind` hook and use `cva` instead. Only `packages/ui` should be impacted.

**Comment by Jighdan** [comment]
I can take care of this

**Comment by QuiiBz** [comment]
Thanks, I'm assigning you the issue - you can also check out the [contributing docs](https://docs.lagon.app/contributing), and you can use the `dev` script inside `packages/ui` to launch the storybook to test your changes.
