### ISSUE TITLE
`CompressionStream` & `DecompressionStream` APIs

### ISSUE THREAD

**Issue by QuiiBz** [lagonapp/lagon#425]
We have support for streaming APIs (`ReadableStream`, `WritableStream`, ...) thanks to [web-stream-polyfill](https://www.npmjs.com/package/web-streams-polyfill), but not for `CompressionStream` & `DecompressionStream`. Can we use an existing polyfill?

https://wicg.github.io/compression/#compression-stream
https://wicg.github.io/compression/#decompression-stream

**Comment by abdullahranginwala** [comment]
I believe we can use the pako library as a fallback implementation to add support for CompressionStream and DecompressionStream APIs. It can provide this support and is easy to integrate. We consider using this library to solve this issue

**Comment by QuiiBz** [comment]
Done in https://github.com/lagonapp/lagon/pull/932!
