### ISSUE TITLE
project name clash

### ISSUE THREAD

**Issue by tomByrer** [lagonapp/lagon#55]
**Describe the bug**
https://www.serverless.com/
Been around for years.  Originally seemed like it was supposed to be an agnostic abstraction, but last 2 years was gobbled up by AWS, who have better lawyers than you ;)

**Comment by QuiiBz** [comment]
Hey, serverless isn't the name of this project, the name is Lagon (https://lagon.app).

I agree that the repo name might be confusing, I'm thinking about renaming it to `lagonapp/lagon` instead of `lagonapp/serverless`. What do you think?

**Comment by tomByrer** [comment]
Just 'lagon' could work.  'lagon-serverless' for SEO without too much .serverless.com confusion I think.

**Comment by QuiiBz** [comment]
Renamed the repo to `lagonapp/lagon` instead of `lagonapp/serverless`. Thanks!
