### ISSUE TITLE
Deployment timestamp wrong

### ISSUE THREAD

**Issue by 20k-ultra** [lagonapp/lagon#695]
What timestamp is used for the deployment ? I deployed a function and the time showed 10:30 AM but my local time is 2:30... I am in Toronto so -4 offset makes sense but it's like applying the offset twice adjusting ? I assume the stored timestamp is UTC so -4 would be correct but it's like another -4 is applied ?

**Comment by QuiiBz** [comment]
By default, Prisma uses UTC to save dates. On the CLI, no extra steps are made to convert this UTC time to your local device time. On the dashboard, the time should already be formatted properly. Are you seeing this issue on the CLI?

**Comment by 20k-ultra** [comment]
I can confirm the issue is so far just in the UI. In the following screenshot we can see that the API responds with the correct timestamp in UTC but the UI tries to normalize it to my locale but something goes wrong.

![image](https://user-images.githubusercontent.com/3946250/228410496-c353a2b2-6cdf-429a-bd1d-23195e02747d.png)

I'll try to find the code that does the rendering of the timestamp to user's locale.
