### ISSUE TITLE
Add the ability to copy tokens

### ISSUE THREAD

**Issue by QuiiBz** [lagonapp/lagon#699]
Currently, the only way to get an auth token is to copy it from the CLI's configuration (`~/.lagon/config.json`). We should add the ability to copy a token's value on the dashboard too:

![Image](https://user-images.githubusercontent.com/43268759/227763078-881f8bd8-d413-44d2-9d6e-964d0ad6fd0a.png)

**Comment by 20k-ultra** [comment]
what is the screenshot of ? A hidden UI that exists or just a mock you'd want implemented ?

**Comment by QuiiBz** [comment]
It's the existing page that is available at https://dash.lagon.app/profile
