### ISSUE TITLE
Randomly asked to re-authenticate when not needed

### ISSUE THREAD

**Issue by 20k-ultra** [lagonapp/lagon#713]
I have experienced a few times where the dashboard asks me to login to Github again. I find it often happens when I am on another tab for awhile.

The interesting thing though, is that I just remove `/auth/signin` from the url and I can continue as if I wasn't prompted to re-auth. I do not think this is a access issue like my tokens are invalid but I can still see data. I just think something on the frontend is prompting me to re-auth incorrectly.

**Comment by 20k-ultra** [comment]
maybe this is related. I opened the console logs when I was prompted to re-auth.

```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error JSON.parse: unexpected character at line 1 column 1 of the JSON data 
Object { error: {…}, url: "/api/auth/session", message: "JSON.parse: unexpected character at line 1 column 1 of the JSON data", client: true }
​
client: true
​
error: Object { message: "JSON.parse: unexpected character at line 1 column 1 of the JSON data", stack: "", name: "SyntaxError" }
​
message: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
​
url: "/api/auth/session"
```

**Comment by 20k-ultra** [comment]
definitely not time based because I left my lagon tab for a few hours and upon returning I wasn't asked to re-auth. I know... one of those annoying bugs to reproduce.

**Comment by QuiiBz** [comment]
Thanks for creating an issue for this bug, I've also noticed it a few times in the past. I also have errors on the server side (lambda on Vercel right now) when this bug occurs:

![image](https://user-images.githubusercontent.com/43268759/228444753-832e3f81-b663-4d8c-a17b-55cedf16297d.png)

Note that you can also refresh your tab when this error occurs, and it will work again without needing to re-authenticate.

**Comment by QuiiBz** [comment]
This looks like an issue from the Redis connection time outing. It's used to create deployments/undeployments: https://github.com/redis/node-redis/issues/2058
