### ISSUE TITLE
Display dashboard version in the dashboard

### ISSUE THREAD

**Issue by 20k-ultra** [lagonapp/lagon#720]
To help with troubleshooting what versions have bugs and if new versions fixed them, knowing the version of the dashboard being used is helpful.

The semver version of the dashboard can also be used as a way for people to learn about what's new. If a user clicks on the version, a modal displaying a changelog will appear showing the version history and what has changed.

The version can either be in the top nav bar as a small font or in the user's dropdown menu (the menu when they click their name).

**Comment by 20k-ultra** [comment]
I added this as a bug by mistake.. meant to be a feature

**Comment by QuiiBz** [comment]
We should also update the deployment settings in Vercel to allow logging in through preview deployments of the dashboard: we probably need to update the callback URL used for OAuth to redirect to $VERCEL_URL

**Comment by QuiiBz** [comment]
Assigning @colinlienard
