### ISSUE TITLE
run pnpm lagon dev will throw module not found error

### ISSUE THREAD

**Issue by await-ovo** [lagonapp/lagon#86]
**Describe the bug**

![Pasted Graphic 1 copy](https://user-images.githubusercontent.com/41503212/178215897-9c251024-0051-4ec5-8ac8-4afc5157533b.png)

**To Reproduce**
1. `mkdir test-lagon && cd test-lagon`
2. `pnpm init  && pnpm add @lagon/cli`
3. `pnpm lagon dev`

**Expected behavior**

The command can be executed successfully. 

**Information:**
 - OS: macOS
 - Node.js Version: v16.15.1
 
 
 It seems related to esbuild  external dependencies with esm format(https://github.com/evanw/esbuild/issues/1958).

**Comment by QuiiBz** [comment]
Btw, let me create an issue to not forgot about adding more tests to catch those issues in the future.

**Comment by QuiiBz** [comment]
Published version `0.0.7` of `@lagon/cli`, you should be able to update to get the fix.
