### ISSUE TITLE
Universal packages version unification

### ISSUE THREAD

**Issue by akitaSummer** [lagonapp/lagon#888]
I think we should put commonly used packages in one package(such as lagon_utils)for version consistency.

**Comment by QuiiBz** [comment]
The goal of splitting into multiple crates is to reduce the complexity and compilation time. We could instead use changesets's [fixed](https://github.com/changesets/changesets/blob/8ede784e5fc3629858a57643fdaab76ffb631520/docs/fixed-packages.md) option to version those crates together.
