### ISSUE TITLE
Lagon sites timeout when behind Cloudflare WARP

### ISSUE THREAD

**Issue by officialpiyush** [lagonapp/lagon#900]
**Describe the bug**
While trying to access a site deployed on lagon (both lagon.dev and custom domain) while being behind a [Cloudflare WARP](https://1.1.1.1), the request times out.

**To Reproduce**
1. Enable Cloudflare WARP
2. Goto any lagon deployed site, example https://ping.lagon.dev/
4. Wait for the response from the server

**Expected behavior**
The site should load normally, like how it would on regular connections.

**Screenshots**
![image](https://github.com/lagonapp/lagon/assets/18086566/35c73ed8-702c-4b86-bb77-fc61ed181a7e)

**Information:**
 - OS: Windows
 - Browser: Chromium (Brave)
 - Version: 1.51.118 (Chromium: 113.0.5672.126)

**Comment by QuiiBz** [comment]
I'm not able to reproduce it on my Mac, but I know someone else got the same issue while using Cloudflare Warp. Could you run the following commands on a terminal and output the logs here?

`dig ping.lagon.dev`
`ping ping.lagon.dev`
`traceroute -a [IP resolved from ping/dig]`

Also, does this issue occurs when enabling 1.1.1.1 and Warp, or only when enabling 1.1.1.1?

![Screenshot 2023-05-27 at 18 10 23](https://github.com/lagonapp/lagon/assets/43268759/ab2f1999-cfef-42b8-b81a-4cf7eddf518c)

**Comment by officialpiyush** [comment]
> I'm not able to reproduce it on my Mac, but I know someone else got the same issue while using Cloudflare Warp. Could you run the following commands on a terminal and output the logs here?
> 
> `dig ping.lagon.dev` `ping ping.lagon.dev` `traceroute -a [IP resolved from ping/dig]`
> 
> Also, does this issue occurs when enabling 1.1.1.1 and Warp, or only when enabling 1.1.1.1?
> 
> ![Screenshot 2023-05-27 at 18 10 23](https://user-images.githubusercontent.com/43268759/241409756-ab2f1999-cfef-42b8-b81a-4cf7eddf518c.png)

Happens only when using Cloudflare WARP (1.1.1.1 & WARP enabled)
![image](https://github.com/lagonapp/lagon/assets/18086566/559de43a-7646-42a6-aa80-f235d1092cd5)

the IP from the ping command gives me an IPv6 address (while using WARP)
![image](https://github.com/lagonapp/lagon/assets/18086566/44383b50-a2e6-495d-95a8-778e84e09c12)

Here is it's traceroute
```
PS> tracert 2402:1f00:8002:100::1

Tracing route to 2402:1f00:8002:100::1 over a maximum of 30 hops

  1    92 ms    92 ms    92 ms  2606:4700:110::1
  2    93 ms    96 ms    94 ms  2400:cb00:35:1000::1
  3    95 ms    93 ms   112 ms  2400:cb00:35:2::2
  4    99 ms     *        *     2001:df5:b800:bb00:0:1:6276:1
  5     *        *        *     Request timed out.
  6   110 ms   101 ms   100 ms  2001:41d0:aaaa:100::3
  7     *        *        *     Request timed out.
  8     *        *       95 ms  2402:1f00:ffff:fe00:1000::1
  9     *       96 ms    96 ms  be10.sin1-sgcs2-g2-nc5.sng.asia [2402:1f00:ffff:fe00::1]
 10    93 ms    95 ms    95 ms  2402:1f00:ffff:fe00:1000::37
 11    96 ms    96 ms    96 ms  2001:41d0:0:50::7:1b
 12     *        *        *     Request timed out.
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out.

Trace complete.
```

**Comment by QuiiBz** [comment]
The issue has been fixed:

I've noticed for some PoPs that our GeoDNS replied with an IPv6 subnet instead of an IPv6 address, but some of our hosting providers require an IPv6 address to resolve the exact machine. Updating these records to always return the correct IPv6 address resolved the issue. Apologize for the inconvenience!
