### ISSUE TITLE
auto get available port in dev

### ISSUE THREAD

**Issue by await-ovo** [lagonapp/lagon#92]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/41503212/178402340-5ad641a3-d638-4dc6-92a5-5043bea9a2aa.png)

Currently, if port 1234 is occupied, an error is thrown directly, but there is no way to change the port.

**Describe the solution you'd like**

* There should be a way to specify the port when dev, for example `lagon dev --port 8000`
* Ability to automatically get available port([get-port-please](https://www.npmjs.com/package/get-port-please))

**Comment by QuiiBz** [comment]
Good idea. We could also add the `--host(name?)` option, which currently defaults to `localhost`.

But not sure about adding another dependency for ports, it should be easily feasible. Next.js does it in a few lines of code: https://github.com/vercel/next.js/blob/9342a6ccc7f59e5de481577be61859cf5372be0e/packages/next/server/lib/start-server.ts#L26

**Comment by await-ovo** [comment]
> Good idea. We could also add the `--host(name?)` option, which currently defaults to `localhost`.
> 
> But not sure about adding another dependency for ports, it should be easily feasible. Next.js does it in a few lines of code: https://github.com/vercel/next.js/blob/9342a6ccc7f59e5de481577be61859cf5372be0e/packages/next/server/lib/start-server.ts#L26

Looks good, I can submit a pr later~
